### PR TITLE
Build and publish to PyPI via CI, use Limited API (Stable ABI)

### LINKED ISSUE #1: Python v3 support
Thanks again for providing this library. :)

I'm updating DRO Trimmer to run on Python v3. Unfortunately, PyOPL only supports Python v2.

It looks like @adambiser has created a fork to support Python v3. I've successfully used it in DRO Trimmer. Would it be possible to publish a new official version of PyOPL with these changes?

https://github.com/Malvineous/pyopl/compare/master...adambiser:pyopl:master

### PR DESCRIPTION
**Pull request by laurence-myers**
- Remove support for Python v2
- Move project metadata into pyproject.toml
  - Add Adam Biser to the list of authors
  - Add myself (Laurence Dougal Myers) to the list of maintainers
  - Add minimum Python version of 3.8
  - Increase version to 2.0 (due to breaking changes)
  - Use SPDX identifier for license, change the classifier to GPLv3
- Replace distutils with setuptools
- Add GitHub Actions CI
  - Build a wheel for every combination of Python version, OS, architecture, and Python implementation (CPython vs PyPy). This is all done for us using [`cibuildwheel`](https://cibuildwheel.readthedocs.org/)
  - Produce a source distribution
  - Publish all to PyPI
    - Uses ODIC (Trusted Publishing), so no extra credentials required in GitHub 🙂 
    - Example PyPI entry, on TestPyPI: https://test.pypi.org/project/PyOPL/
  - Triggered whenever a GitHub release is published
    - Example release: https://github.com/Malvineous/pyopl/releases/tag/release%2Fpre-2.0-3
- Use the Limited API (Static ABI) when building wheels for Python v3.11 or higher. This should allow the wheel to run on any future Python version.
  - setup.py: When building Python v3.11 or higher:
    - Set macro `Py_LIMITED_API`
    - Set option `py_limited_api`
    - Add tags `cp311` and `abi3` (cp311 is the lowest supported version)
  - pyopl.cpp:
    - Use a heap-allocated (dynamic) type to define `PyOPLType`. (Static types aren't supported by the Limited API.)
    - Replace `tp_alloc()` call with direct call to `PyType_GenericAlloc`. (The type object doesn't seem to be accessible in the Limited API, and I couldn't work out how to look up the `tp_alloc` pointer without a type object, so I've just assumed it will always use the default generic allocator.)
- Convert `README` to Markdown
- pyopl.pyi: give type hint `bytearray` for `buffer`
- .gitignore: ignore IDEA project dir, wheel build dirs, and venv (virtual environment) dir

## Minimum supported version

The minimum supported version of Python is v3.8, since this is the oldest actively maintained version.

<details>
<summary>Python release status chart</summary>
2024-01-27 12_18_24-Status of Python versions — Mozilla Firefox

https://devguide.python.org/versions/
</details>

## ABI3 audit

It's possible to tag a wheel as adhering to `abi3` when it doesn't really, so I ran [`abi3audit`](https://github.com/trailofbits/abi3audit), which didn't find any problems.

2024-01-27 12_36_59-pyopl – Repository Diff_ pyopl cpp

## Testing

I've only tested the module on Python 3.11, Windows 64-bit.

## PyPI entry

https://test.pypi.org/project/PyOPL/

Here's how the PyPI entry looks.

<details>
<summary>Click to see screenshots</summary>
2024-01-27 12_44_20-PyOPL · TestPyPI — Mozilla Firefox
2024-01-27 12_44_40-PyOPL · TestPyPI — Mozilla Firefox
2024-01-27 12_44_49-PyOPL · TestPyPI — Mozilla Firefox
</details>

## CI workflow

Here's an example CI run.

https://github.com/Malvineous/pyopl/actions/runs/7668724733

<details>
<summary>Click to see screenshots</summary>
2024-01-27 12_48_41-release_pre-2 0-3 · Malvineous_pyopl@93bdb92 — Mozilla Firefox
2024-01-27 12_48_36-release_pre-2 0-3 · Malvineous_pyopl@93bdb92 — Mozilla Firefox
2024-01-27 12_48_29-release_pre-2 0-3 · Malvineous_pyopl@93bdb92 — Mozilla Firefox

Building on Python 3.12 is skipped, because the build for v3.11 supports the stable ABI, so no need for a new wheel.

2024-01-27 12_49_10-release_pre-2 0-3 · Malvineous_pyopl@93bdb92 — Mozilla Firefox
</details>

Closes #1

### CODE REVIEW

**Comment by laurence-myers** [comment]
@adambiser If you have time, I'd appreciate if you could have a quick look over my changes, particularly the C++ side.

**Review by Malvineous — APPROVED** [review]
Can't comment too much on the accuracy of the code as it's been years since I've been involved with Python, but nothing immediately stands out as problematic - it looks good.  Thanks for taking the time to do all these updates!

**Review by adambiser — APPROVED** [review]
The changes look correct to me.

**Comment by laurence-myers** [comment]
Thank you both for the reviews. 🙂 

I fixed up some issues, and added a simple regression test, mostly to make sure the wheels run properly on each build.

I'll merge the changes and publish a new version to PyPI soon(ish, when I feel up to it).

**Pull request merged**
